name: Python build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install-all

    - name: Lint
      run: make lint

    - name: Run tests
      run: make test

    - name: Create package
      run: make pkg

    - name: Upload package artifacts
      uses: actions/upload-artifact@v2
      with:
        name: package-artifacts
        path: dist/*
