name: Python build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: azure/docker-login@v1
      with:
        login-server: cr.kruhlmann.dev
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install-all
    - name: Lint
      run: make lint
    - name: Run tests
      run: make test
    - name: Create package
      run: make pkg
    - name: Build image
      run: docker build . -t cr.kruhlmann.dev/ChronoAtlas/wikidata-producer
    - name: Publish image
      run: docker push cr.kruhlmann.dev/ChronoAtlas/wikidata-producer
    - name: Upload package artifacts
      uses: actions/upload-artifact@v2
      with:
        name: package-artifacts
        path: dist/*
